## EVERFOREST
# [colors.bright]
# black = "#4b565c"
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"

# [colors.normal]
# black = "#4b565c" 
# blue = "#7fbbb3"
# cyan = "#83c092"
# green = "#a7c080"
# magenta = "#d699b6"
# red = "#e67e80"
# white = "#d3c6aa"
# yellow = "#dbbc7f"

# [colors.primary]
# background = "#2D353B"
# foreground = "#d3c6aa"

## ZENBURN
# [colors.primary]
# background = '#3A3A3A'
# foreground = '#DCDCCC'

# # Normal colors
# [colors.normal]
# black   = '#1E2320'
# red     = '#D78787'
# green   = '#60B48A'
# yellow  = '#DFAF8F'
# # blue    = '#506070'
# blue    = '#93E0E3'
# magenta = '#DC8CC3'
# cyan    = '#8CD0D3'
# white   = '#DCDCCC'

# # Bright colors
# [colors.bright]
# black   = '#709080'
# red     = '#DCA3A3'
# green   = '#C3BF9F'
# yellow  = '#F0DFAF'
# blue    = '#94BFF3'
# magenta = '#EC93D3'
# cyan    = '#93E0E3'
# white   = '#FFFFFF'

# PARADISE

# Default colors
[colors.primary]
background = '#151515'
foreground = '#E8E3E3'

# Normal colors
[colors.normal]
black =   '#151515'
red =     '#B66467'
green =   '#8C977D'
yellow =  '#D9BC8C'
blue =    '#8DA3B9'
magenta = '#A988B0'
cyan =    '#8AA6A2'
white =   '#E8E3E3'

[colors.bright]
# Bright colors
black =   '#424242'
red =     '#B66467'
green =   '#8C977D'
yellow =  '#D9BC8C'
blue =    '#8DA3B9'
magenta = '#A988B0'
cyan =    '#8AA6A2'
white =   '#E8E3E3'




[font]
size = 12.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.90
blur = true
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 36

[window.padding]
x = 30
y = 30
