#!/usr/bin/env sh
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          on             \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               on            \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        0.0            \
    normal_window_opacity        1.00          \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xffd3c6aa     \
    normal_window_border_color   0xff2b3339      \
    window_border_width          2              \ window_border_radius         0             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   vertical           \
    auto_balance                 on            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   12             \
    layout                       bsp            \
    mouse_modifier               alt             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# yabai -m config --space 5 \
# 	top_padding 40 \
# 	window_gap = 20 

# yabai -m config --space 6 \
# 	top_padding 40 \
# 	window_gap = 20  

# yabai -m config --space 7 \
# 	top_padding 40 \
# 	window_gap = 20  

# yabai -m config --space 8 \
# 	top_padding 40 \
# 	window_gap = 20  

yabai -m rule --add app="^(LuLu|Vimac|Calculator|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|Calendar|Todoist|Geneious Prime|Numi|Finder|Alacritty|TextEdit)$" manage=off


echo "yabai configuration loaded.."

yabai -m config --dislay 0 external_bar all:30:0
yabai -m config --display 1 external_all:0:0
yabai -m rule --add app=".*" layer = normal

